/*
 * File: app/store/Attachments.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.store.Attachments', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        autoLoad: true,
        storeId: 'Attachments',
        fields: [
            {
                name: 'type'
            },
            {
                name: 'id'
            },
            {
                name: 'picture'
            },
            {
                name: 'icon'
            },
            {
                name: 'name'
            },
            {
                name: 'lat'
            },
            {
                name: 'long'
            }
        ],
        listeners: [
            {
                fn: 'onStoreAddrecords',
                event: 'addrecords'
            },
            {
                fn: 'onStoreRemoverecords',
                event: 'removerecords'
            }
        ]
    },

    onStoreAddrecords: function(store, records, eOpts) {
        var alist=Ext.ComponentQuery.query('#attachments');
        if (alist[0])
        {
            alist[0].setHidden(false)
        }

    },

    onStoreRemoverecords: function(store, records, indices, eOpts) {
        if (store.getCount()==0)
        {
            var alist=Ext.ComponentQuery.query('#attachments');
            if (alist[0])
            {
                alist[0].setHidden(true)
            }
        }
    }

});