/*
 * File: app/store/Chat.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.store.Chat', {
    extend: 'Ext.data.Store',

    requires: [
        'VKM.model.Chat',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.util.Grouper'
    ],

    config: {
        clearOnPageLoad: false,
        groupDir: 'ASC',
        model: 'VKM.model.Chat',
        pageSize: 10,
        storeId: 'Chat',
        proxy: {
            type: 'rest',
            filterParam: 'undefinded',
            groupParam: 'undefinded',
            limitParam: 'count',
            startParam: 'offset',
            reader: {
                type: 'json',
                rootProperty: 'response.items',
                totalProperty: 'response.count'
            }
        },
        sorters: {
            property: 'date'
        },
        grouper: {
            groupFn: function(item) {
                if(item.get('id')==0)
                {
                    return('');
                }
                else
                {
                    return moment(parseInt(item.get('date'))*1000).format('D MMMM YYYY');
                }
            },
            sortProperty: 'date'
        },
        listeners: [
            {
                fn: 'onStoreLoad',
                event: 'load'
            }
        ]
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {
        // console.log('chat');
        // console.log(records);
    }

});