/*
 * File: app/store/FriendsInCommon.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.store.FriendsInCommon', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    config: {
        clearOnPageLoad: false,
        pageSize: 10000,
        storeId: 'FriendsInCommon',
        syncRemovedRecords: false,
        proxy: {
            type: 'rest',
            filterParam: 'undefined',
            groupParam: 'undefined',
            limitParam: 'count',
            startParam: 'offset',
            url: 'https://api.vk.com/method/execute.friendsInCommon',
            appendId: false,
            reader: {
                type: 'json',
                rootProperty: 'response'
            }
        },
        fields: [
            {
                name: 'id'
            },
            {
                name: 'first_name'
            },
            {
                name: 'last_name'
            },
            {
                name: 'photo_50'
            },
            {
                name: 'photo_100'
            }
        ]
    }
});