/*
 * File: app/store/Images.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.store.Images', {
    extend: 'Ext.data.Store',

    requires: [
        'VKM.model.Images',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    config: {
        clearOnPageLoad: false,
        model: 'VKM.model.Images',
        pageSize: 10,
        storeId: 'Images',
        proxy: {
            type: 'rest',
            filterParam: 'undefined',
            groupParam: 'undefined',
            limitParam: 'count',
            sortParam: 'undefined',
            startParam: 'offset',
            reader: {
                type: 'json',
                rootProperty: 'response.items',
                totalProperty: 'response.count'
            }
        }
    }
});