/*
 * File: app/view/AlbumItem.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.view.AlbumItem', {
    extend: 'Ext.dataview.component.DataItem',
    alias: 'widget.albumitem',

    requires: [
        'Ext.Img'
    ],

    config: {
        padding: 10,
        layout: 'hbox',
        itemCls: 'x-list-item',
        items: [
            {
                xtype: 'image',
                cls: 'x-white',
                docked: 'left',
                height: 150,
                itemId: 'albumCover',
                style: {
                    'background-size': 'cover'
                },
                width: 150
            },
            {
                xtype: 'image',
                cls: 'x-white',
                docked: 'left',
                height: 150,
                itemId: 'albumCover1',
                style: {
                    'background-size': 'cover'
                },
                width: 150
            }
        ]
    },

    updateRecord: function(record) {
        // Provide an implementation to update this container's child items
        if(!this.counter)
        {
            this.counter =1;
        }
        else
        {
            this.counter+=1;
        }
        if (this.counter % 2 == 0)
        {
            this.down('#albumCover').setSrc(record.get('thumb_src'));
            this.down('#albumCover').setHtml(record.get('title')+'('+record.get('size')+')');
        }
        else
        {
            this.down('#albumCover1').setSrc(record.get('thumb_src'));
            this.down('#albumCover1').setHtml(record.get('title')+'('+record.get('size')+')');
        }
        //this.down('#albumDescription').setHtml('<div>'+record.get('title')+'</div><br/><div>'+record.get('size')+' '+Ext.util.Inflector.pluralize(ux.locale.Manager.get('labels.Photo'))); //record.get('title'));

    }

});