/*
 * File: app/view/AlbumList.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.view.AlbumList', {
    extend: 'Ext.dataview.DataView',
    alias: 'widget.albumlist',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        cls: 'dataview-inline',
        itemId: 'albumList',
        padding: '20px',
        inline: true,
        store: 'Albums',
        itemTpl: [
            '<div class="img" style="background-image: url({thumb_src});">{title}({size})</div>'
        ]
    }

});