/*
 * File: app/view/ChatList.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.view.ChatList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.chatlist',

    config: {
        itemId: 'mydataview2',
        deselectOnContainerClick: false,
        defaultType: 'messageItem',
        itemCls: 'x-list-item',
        scrollToTopOnRefresh: false,
        selectedCls: 'selectedMask',
        store: 'Chat',
        triggerEvent: 'itemdoubletap',
        grouped: true,
        listeners: [
            {
                fn: 'onMydataview2Initialize',
                event: 'initialize'
            },
            {
                fn: 'onMydataview2Painted',
                event: 'painted'
            }
        ]
    },

    onMydataview2Initialize: function(component, eOpts) {
        component.setPlugins({type:'listpagingreverse', autoPaging: true});
    },

    onMydataview2Painted: function(element, eOpts) {
        // if (VKM.app.globals.settings.chatSelection=='longclick')
        // {
        //     this.setTriggerEvent('itemtapHold');
        // }
        // else
        // {
        //     this.setTriggerEvent('itemdoubletap');
        // }

    },

    onScrollEnd: function(scroller, x, y) {
        // var list = this;

        // if (!this.loading && y >= scroller.maxPosition.y) {
        //     this.loading=true;
        //     this.fireEvent('loadNext',list);
        // };
        // console.log('scroll');
        // if (!this.loading && y <= scroller.minPosition.y) {
        //     this.loading=true;
        //     this.fireEvent('loadPrevious',list);
        // };
    }

});