/*
 * File: app/view/ContactsList.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.view.ContactsList', {
    extend: 'Ext.dataview.DataView',
    alias: 'widget.contactslist',

    config: {
        deselectOnContainerClick: false,
        mode: 'MULTI',
        defaultType: 'contactItem',
        itemCls: 'x-list-item',
        maxItemCache: 50,
        scrollToTopOnRefresh: false,
        store: 'Friends',
        useComponents: true
    }

});