/*
 * File: app/view/MessagesList.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.view.MessagesList', {
    extend: 'Ext.dataview.DataView',
    alias: 'widget.messageslist',

    config: {
        itemId: 'mydataview1',
        deselectOnContainerClick: false,
        defaultType: 'messageItem',
        itemCls: 'x-list-item',
        maxItemCache: 50,
        scrollToTopOnRefresh: false,
        store: 'AllMessages',
        useComponents: true,
        listeners: [
            {
                fn: 'onMydataview1Refresh',
                event: 'refresh'
            }
        ]
    },

    onMydataview1Refresh: function(dataview, eOpts) {
        // var component=dataview;
        // var scroller = component.getScrollable().getScroller(),
        //     store    = component.getStore();

        // component.scroller=scroller;
        // scroller.list=component;
        // scroller.on({
        //     scrollend: component.onScrollEnd,
        //     scope: component
        // });

        // scroller.on({
        //     scrollend: component.onScrollEnd,
        //     scope: component
        // });

    },

    onScrollEnd: function(scroller, x, y) {
        // var list = this;

        // if (!this.loading && y >= scroller.maxPosition.y) {
        //     this.loading=true;
        //     this.fireEvent('loadNext',list);
        // };
        // if (!this.loading && y <= scroller.minPosition.y) {
        //     this.loading=true;
        //     this.fireEvent('loadPrevious',list);
        // };
    }

});