/*
 * File: app/model/User.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.model.User', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        identifier: {
            type: 'simple'
        },
        fields: [
            {
                name: 'id'
            },
            {
                name: 'first_name'
            },
            {
                name: 'last_name'
            },
            {
                name: 'sex'
            },
            {
                name: 'bdate'
            },
            {
                name: 'city'
            },
            {
                name: 'country'
            },
            {
                name: 'photo_50'
            },
            {
                name: 'photo_100'
            },
            {
                name: 'photo_200_orig'
            },
            {
                name: 'photo_200'
            },
            {
                name: 'photo_400_orig'
            },
            {
                name: 'photo_max'
            },
            {
                name: 'photo_max_orig'
            },
            {
                name: 'online'
            },
            {
                name: 'lists'
            },
            {
                name: 'screen_name'
            },
            {
                name: 'has_mobile'
            },
            {
                name: 'contacts'
            },
            {
                name: 'connections'
            },
            {
                name: 'site'
            },
            {
                name: 'education'
            },
            {
                name: 'universities'
            },
            {
                name: 'schools'
            },
            {
                name: 'can_post'
            },
            {
                name: 'status'
            },
            {
                name: 'last_seen'
            },
            {
                name: 'relation'
            },
            {
                name: 'counters'
            },
            {
                name: 'can_write_private_message'
            },
            {
                name: 'important'
            },
            {
                name: 'friendType'
            },
            {
                name: 'isFriend'
            },
            {
                name: 'mobile_phone'
            },
            {
                name: 'home_phone'
            },
            {
                name: 'university_name'
            },
            {
                name: 'cityName'
            },
            {
                name: 'countryName'
            }
        ]
    }
});