/*
 * File: app/controller/DataLoader.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VKM.controller.DataLoader', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            chatHeader: 'container#chatHeader'
        }
    },

    go: function(url, params, callback, extraData, method) {
        var dataController=VKM.app.getController('DataLoader');
        if(!method)
        {
            method='GET';
        };
        if(!callback)
        {
            callback=Ext.emptyFn;
        }

        Ext.Ajax.request({
            url: url,
            params:params,
            method: method,
            disableCaching: true,
            extraData:extraData,
            callback: function(request, success,response,extraData) {
                //console.log(response);
                if (success)
                {
                    if(response)
                    var JsonResponse=JSON.parse(response.responseText);
                    if (!JsonResponse.error)
                    {
        //                 console.log(response);
        //                 console.log(JsonResponse);
                        callback(response,JsonResponse);
                    }
                    else
                    {
                        console.log(response);
                        console.log(JsonResponse);
                        if (JsonResponse.error.error_code==6||VKM.app.globals.doNotReconnect)
                        {
                            var extraData1=response.request.options.extraData;
                            var callback1=callback;
                            var params1=response.request.options.params;
                            var url1=response.request.options.url;
                            var method1=response.request.options.method;
                            setTimeout(dataController.go(url1,params1,callback1,extraData1,method1),1500);
                        }
                        else
                        {
                            if (JsonResponse.error.error_code==5)
                            {
                                var extraData1=response.request.options.extraData;
                                var callback1=callback;
                                var params1=response.request.options.params;
                                var url1=response.request.options.url;
                                var method1=response.request.options.method;
                                VKM.app.getController('Login').relogin(url1,params1,callback1,extraData1);
                            }
                            else

                            {
                                alert(JsonResponse.error.error_msg)
                            }
                        }
                    }
                }
                else

                {
                    alert(response.responseText)
                }
            }
        })
    },

    uploadProfileStep2: function(response, users) {
        var formData = new FormData();
        var dataController=VKM.app.getController('DataLoader');
        formData.append("photo", document.getElementById("photoToUpload1").files[0]);
        if(users.response&&users.response.upload_url)
        {
            var client = new XMLHttpRequest();
            client.onreadystatechange = function ()
            {
                if (client.readyState == 4 && client.status == 200)
                {
                    alert(client.response);
                }
            }
            //client.open("POST",users.response.upload_url, true);
            var progressIndicator = Ext.create("Ext.ProgressIndicator", {
                loadingText: "Uploading: {percent}%"
            });

            //            client.send(formData);
            //            /* Send to server */
            Ext.Ajax.request({
                url:users.response.upload_url,
                method: 'POST',
                enctype:'multipart/form-data',
                data:formData,
                progress: progressIndicator,
                //isUpload:true,
                // binaryData:formData,
                xhr2:true,
                callback:function(request,success,response)
                {

                    var controller=VKM.app.getController('Contacts');
                    var dataController=VKM.app.getController('DataLoader');
                    var data=JSON.parse(response.responseText);
                    controller.uploadOverlay.destroy();


                    var url='https://api.vk.com/method/photos.saveProfilePhoto'; //photos.saveProfilePhoto';
                    var params=
                        {
                            v:'5.4',
                            access_token:VKM.app.globals.authData['access_token'],
                            server:data.server,
                            photo:data.photo,
                            hash:data.hash
                        };
                    dataController.go(url,params,dataController.uploadProfileStep3);
                }


            })


        }
    },

    uploadChatStep2: function(response, users) {
        var formData = new FormData();
        var dataController=VKM.app.getController('DataLoader');
        formData.append("file", document.getElementById("photoToUpload10").files[0]);
        if(users.response&&users.response.upload_url)
        {
            var client = new XMLHttpRequest();
            client.onreadystatechange = function ()
            {
                if (client.readyState == 4 && client.status == 200)
                {
                    alert(client.response);
                }
            }
            //client.open("POST",users.response.upload_url, true);
            var progressIndicator = Ext.create("Ext.ProgressIndicator", {
                loadingText: "Uploading: {percent}%"
            });

            //            client.send(formData);
            //            /* Send to server */
            Ext.Ajax.request({
                url:users.response.upload_url,
                method: 'POST',
                enctype:'multipart/form-data',
                data:formData,
                progress: progressIndicator,
                //isUpload:true,
                // binaryData:formData,
                xhr2:true,
                callback:function(request,success,response)
                {

                    if(success)
                    {
                        var controller=VKM.app.getController('Utils');
                        var dataController=VKM.app.getController('DataLoader');
                        var data=JSON.parse(response.responseText);
                        controller.uploadOverlay.destroy();
                        //console.log(data);

                        var url='https://api.vk.com/method/messages.setChatPhoto'; //photos.saveProfilePhoto';
                        var params=
                            {
                                v:'5.4',
                                access_token:VKM.app.globals.authData['access_token'],
                                file:data
                            };
                        dataController.go(url,params,dataController.uploadChatStep3);
                    }
                    else
                    {
                        alert(response.responseText)
                    }
                }


            })


        }
    },

    uploadProfileStep3: function(response, users) {

        if(users.response)

        {
            console.log(users.response);

            //     if (!VKM.app.globals.me)
        //     {

            var user=Ext.getStore('Users').getById(VKM.app.globals.authData.user_id);
            user.set('photo_50',users.response.photo_src_small);
            user.set('photo_200',users.response.photo_src);
            user.set('photo_100',users.response.photo_src);
            Ext.ComponentQuery.query('#ownerUserPhoto')[0].setHtml('<img src="'+users.response.photo_src+'"" ></img>')

            var controller=VKM.app.getController('InitDataLoader');
            controller.loadUnreadMessagesStep1(false,true);

        }
    },

    uploadChatStep3: function(response, users) {
        console.log(users.response);
        if(users.response)

        {


        //     //     if (!VKM.app.globals.me)
        // //     {

        //     var user=Ext.getStore('Users').getById(VKM.app.globals.authData.user_id);
        //     user.set('photo_50',users.response.photo_src_small);
        //     user.set('photo_200',users.response.photo_src);
        //     user.set('photo_100',users.response.photo_src);
            var chatHeader=Ext.ComponentQuery.query('#chatHeader');
            if(chatHeader)
            {
               chatHeader[0].down('#avatar').setSrc(users.response.chat.photo_50);
            }
            Ext.ComponentQuery.query('#chatProfilePhoto')[0].setHtml('<img src="'+users.response.chat.photo_200+'"" ></img>')

        //     var controller=VKM.app.getController('InitDataLoader');
        //     controller.loadUnreadMessagesStep1(false,true);

        }
    },

    uploadFileStep2: function(request, users) {
        var formData = new FormData();
        var dataController=VKM.app.getController('DataLoader');
        formData.append("photo", document.getElementById("photoToUpload1").files[0]);
        if(users.response&&users.response.upload_url)
        {
            var client = new XMLHttpRequest();
            client.onreadystatechange = function ()
            {
                if (client.readyState == 4 && client.status == 200)
                {
                    alert(client.response);
                }
            }
            //client.open("POST",users.response.upload_url, true);
            var progressIndicator = Ext.create("Ext.ProgressIndicator", {
                loadingText: "Uploading: {percent}%"
            });

            //            client.send(formData);
            //            /* Send to server */
            Ext.Ajax.request({
                url:users.response.upload_url,
                method: 'POST',
                enctype:'multipart/form-data',
                data:formData,
                progress: progressIndicator,
                //isUpload:true,
                // binaryData:formData,
                xhr2:true,
                callback:function(request,success,response)
                {
                    if(success)
                    {
                        var controller=VKM.app.getController('Dialogues');
                        var dataController=VKM.app.getController('DataLoader');
                        var data=JSON.parse(response.responseText);
                        controller.uploadOverlay.destroy();


                        var url='https://api.vk.com/method/photos.saveMessagesPhoto'; //photos.saveProfilePhoto';
                        var params=
                            {
                                v:'5.4',
                                access_token:VKM.app.globals.authData['access_token'],
                                server:data.server,
                                photo:data.photo,
                                hash:data.hash
                            };
                        dataController.go(url,params,dataController.uploadFileStep3);
                    }
                    else
                    {
                        alert(response.responseText)
                    }
                }


            })


        }
    },

    uploadDocStep2: function(request, users) {
        var formData = new FormData();
        var dataController=VKM.app.getController('DataLoader');
        console.log(document.getElementById("docToUpload1").files[0]);
        formData.append("file", document.getElementById("docToUpload1").files[0]);
        if(users.response&&users.response.upload_url)
        {
            var client = new XMLHttpRequest();
            client.onreadystatechange = function ()
            {
                if (client.readyState == 4 && client.status == 200)
                {
                    alert(client.response);
                }
            }
            //client.open("POST",users.response.upload_url, true);
            var progressIndicator = Ext.create("Ext.ProgressIndicator", {
                loadingText: "Uploading: {percent}%"
            });

            //            client.send(formData);
            //            /* Send to server */
            Ext.Ajax.request({
                url:users.response.upload_url,
                method: 'POST',
                enctype:'multipart/form-data',
                data:formData,
                progress: progressIndicator,
                //isUpload:true,
                // binaryData:formData,
                xhr2:true,
                callback:function(request,success,response)
                {
                    if(success)
                    {
                        var controller=VKM.app.getController('Dialogues');
                        var dataController=VKM.app.getController('DataLoader');
                        var data=JSON.parse(response.responseText);
                        controller.uploadOverlay.destroy();


                        var url='https://api.vk.com/method/docs.save'; //photos.saveProfilePhoto';
                        var params=
                            {
                                v:'5.4',
                                access_token:VKM.app.globals.authData['access_token'],
                                file:data.file

                            };
                        dataController.go(url,params,dataController.uploadDocStep3);
                    }
                    else
                    {
                        alert(response.responseText)
                    }
                }


            })


        }
    },

    uploadDocStep3: function(response, users) {
        console.log(users.response);
        if(users.response[0]&&users.response[0].id)
        {
            Ext.getStore('Docs').add(users.response[0]);
            var icon="resources/images/ext/128/"+users.response[0].ext.toUpperCase()+'.jpg';
            if (!VKM.app.globals.docIcons[users.response[0].ext.toUpperCase()])
            {
                icon="resources/images/ext/128/Default.jpg";
            }
            var attachmentStore=Ext.getStore('Attachments');
            var attachment={
                type:'doc',
                name:users.response[0].title+'('+users.response[0].size+')',
                id:'doc'+users.response[0].owner_id+'_'+users.response[0].id,
                icon:icon
            };
            attachmentStore.add(attachment);
            console.log(attachment);
        }
    },

    uploadFileStep3: function(response, users) {
        if(users.response[0]&&users.response[0].id)
        {

            var attachmentStore=Ext.getStore('Attachments');
            var attachment={
                picture:users.response[0].photo_130,
                name:'',
                id:'photo'+users.response[0].owner_id+'_'+users.response[0].id
            };
            attachmentStore.add(attachment);
            console.log(attachmentStore);

        }
    },

    uploadAuidoStep2: function(request, users) {
        var formData = new FormData();
        var dataController=VKM.app.getController('DataLoader');
        formData.append("file", document.getElementById("audioToUpload1").files[0]);
        if(users.response&&users.response.upload_url)
        {
            var client = new XMLHttpRequest();
            client.onreadystatechange = function ()
            {
                if (client.readyState == 4 && client.status == 200)
                {
                    alert(client.response);
                }
            }
            //client.open("POST",users.response.upload_url, true);
            var progressIndicator = Ext.create("Ext.ProgressIndicator", {
                loadingText: "Uploading: {percent}%"
            });

            //            client.send(formData);
            //            /* Send to server */
            Ext.Ajax.request({
                url:users.response.upload_url,
                method: 'POST',
                enctype:'multipart/form-data',
                data:formData,
                progress: progressIndicator,
                //isUpload:true,
                // binaryData:formData,
                xhr2:true,
                callback:function(request,success,response)
                {

                    console.log(arguments);
                    if(success)
                    {
                        var controller=VKM.app.getController('Dialogues');
                        var dataController=VKM.app.getController('DataLoader');
                        var data=JSON.parse(response.responseText);
                        controller.uploadOverlay.destroy();


                        var url='https://api.vk.com/method/audio.save'; //photos.saveProfilePhoto';
                        var params=
                            {
                                v:'5.4',
                                access_token:VKM.app.globals.authData['access_token'],
                                server:data.server,
                                audio:data.audio,
                                hash:data.hash
                            };
                        dataController.go(url,params,dataController.uploadAudioStep3);
                    }
                    else
                    {
                        alert(response.responseText)
                    }
                }


            })


        }
    },

    uploadAudioStep3: function(response, users) {
        if(users.response.id)
        {

            var attachment={
                title:users.response.title,
                artist:users.response.artist,
                id:users.response.id,
                owner_id:users.response.owner_id,
                duration:users.response.duration,
                url:users.response.url
            };
            Ext.getStore('Audios').add(attachment);


            var attachmentStore=Ext.getStore('Attachments');
            var attachment={
                type:'audio',
                name:users.response.artist+', '+users.response.title,
                id:'audio'+users.response.owner_id+'_'+users.response.id
            };
            attachmentStore.add(attachment);

        }
    }

});